# Maintainer: Berk Küçük <dev.berkkucukk@gmail.com>
#
# maze-secureboot — the Secure Boot / Unified Kernel Image machinery that keeps
# a Maze system bootable across kernel updates.
#
# WHY THIS PACKAGE EXISTS
# -----------------------
# Every file shipped here used to be written per-machine, as inline heredocs, by
# the installer (`deploy-to-target.sh`) into /usr/local/bin, /etc/pacman.d/hooks,
# /etc/kernel/install.d and /etc/systemd/system. That made them UNREACHABLE: a
# bug in the signer, or an upstream systemd change that broke the kernel-install
# contract, could never be fixed on an already-installed machine — pacman does
# not own those files, so no update could ever replace them. The one part of the
# system whose failure mode is "the machine does not boot" was the one part with
# no update path.
#
# Packaging it fixes exactly that: a fix is now `pkgrel++` + publish to
# [mazelinux], and every Maze machine picks it up on the next `pacman -Syu`
# (maze-meta depends on this package, so the update reaches existing installs).
#
# WHAT STAYS PER-MACHINE
# ----------------------
# Only the secrets and the machine-specific bits, still generated by the
# installer and NOT owned by any package:
#   /var/lib/maze-secureboot/MOK.{key,crt,cer}   per-machine signing key
#   /var/lib/maze-secureboot/{shim,mm}x64.efi    shim binaries copied off the ISO
#   /etc/kernel/{cmdline,install.conf}           boot cmdline + layout=uki
#   the "Maze Linux" NVRAM entry
#
# MIGRATION OFF THE OLD LAYOUT
# ----------------------------
# See maze-secureboot.install. Machines installed from an older ISO carry
# installer-written copies at the old paths, and those SHADOW the packaged ones
# (a hook in /etc/pacman.d/hooks overrides the same-named hook in
# /usr/share/libalpm/hooks; likewise /etc/kernel/install.d over
# /usr/lib/kernel/install.d and /etc/systemd/system over /usr/lib/systemd/system).
# The scriptlet removes them and leaves exec shims behind at the old
# /usr/local/bin paths so nothing that still references them can break.

pkgname=maze-secureboot
pkgver=1.2.0
pkgrel=15
pkgdesc="Maze Linux Secure Boot chain — UKI rebuild, MOK signing, and a boot-chain check that blocks unsafe reboots"
arch=('any')
url="https://mazelinux.berkkucukk.com.tr"
license=('GPL3')
depends=(
  'systemd'          # kernel-install, bootctl, the systemd EFI stub
  'systemd-ukify'    # ukify — kernel-install's 60-ukify.install plugin (layout=uki)
  'sbsigntools'      # sbsign / sbverify
  'binutils'         # objcopy — reads the UKI's PE .uname section (fallback match)
  'util-linux'       # flock — serialises the overlapping signer invocations
  'mkinitcpio'       # initramfs generator kernel-install's 50-mkinitcpio.install drives
)
optdepends=(
  'mokutil: enrol the machine MOK key, and let maze-boot-check read the Secure Boot state'
  'libnotify: desktop warning at login when the boot chain is unsafe'
  'shim-signed: the Microsoft-signed first stage (installed by the ISO into /var/lib/maze-secureboot)'
  'efibootmgr: create/inspect the "Maze Linux" NVRAM boot entry'
)
# Migration + unit enablement. Arch forbids doing either from package().
install="${pkgname}.install"
# Both are admin-disableable notification surfaces; preserve local edits.
backup=(
  'etc/xdg/autostart/maze-boot-warning.desktop'
  'etc/profile.d/maze-boot-warning.sh'
)
source=()

package() {
  # Payload tree sits next to this PKGBUILD, mirroring the target filesystem.
  cp -a "${startdir}/maze-secureboot/usr" "${pkgdir}/usr"
  cp -a "${startdir}/maze-secureboot/etc" "${pkgdir}/etc"

  # The flag file lives here. Ship the directory so nothing has to guess whether
  # it exists before writing to it.
  install -dm755 "${pkgdir}/var/lib/maze"

  # Normalise permissions: every helper and the kernel-install plugin must be
  # executable, everything else is plain data.
  chmod 755 "${pkgdir}"/usr/bin/maze-sb-sign \
            "${pkgdir}"/usr/bin/maze-kernel-install-add \
            "${pkgdir}"/usr/bin/maze-initramfs-rebuild \
            "${pkgdir}"/usr/bin/maze-boot-check \
            "${pkgdir}"/usr/bin/maze-boot-guard \
            "${pkgdir}"/usr/bin/maze-boot-notify \
            "${pkgdir}"/usr/bin/maze-boot-entries \
            "${pkgdir}"/usr/lib/kernel/install.d/95-maze-sb-sign.install
  chmod 644 "${pkgdir}"/usr/share/libalpm/hooks/* \
            "${pkgdir}"/usr/lib/systemd/system/maze-sb-resign.* \
            "${pkgdir}"/usr/lib/systemd/system/maze-boot-guard.* \
            "${pkgdir}"/usr/lib/systemd/system/maze-boot-check.* \
            "${pkgdir}"/usr/lib/systemd/system/systemd-boot-update.service.d/*.conf \
            "${pkgdir}"/usr/lib/systemd/system/emergency.service.d/*.conf \
            "${pkgdir}"/usr/lib/systemd/system/rescue.service.d/*.conf \
            "${pkgdir}"/usr/lib/systemd/system-preset/*.preset \
            "${pkgdir}"/etc/xdg/autostart/*.desktop \
            "${pkgdir}"/etc/profile.d/*.sh
}
